<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bucket Sort Simulation</title>
    <link rel="stylesheet" href="ds_style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet">
    <style>
        .sim-container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }

        .buckets-grid {
            display: grid;
            grid-template-columns: repeat(5, 1fr); /* 5 buckets for demo */
            gap: 20px;
            margin-bottom: 2rem;
        }

        .bucket {
            min-height: 250px;
            background: rgba(102, 126, 234, 0.05);
            border: 2px dashed var(--border-color);
            border-radius: 10px;
            padding: 10px;
            position: relative;
        }

        .bucket-label {
            position: absolute;
            top: -25px;
            width: 100%;
            text-align: center;
            font-weight: bold;
            color: var(--text-main);
            left: 0;
        }

        .array-container {
            display: flex;
            justify-content: center;
            gap: 15px;
            margin-bottom: 3rem;
            min-height: 60px;
            flex-wrap: wrap;
        }

        .num-block {
            padding: 10px 15px;
            background: white;
            border: 2px solid var(--primary-color);
            border-radius: 8px;
            font-weight: bold;
            font-family: 'Fira Code', monospace;
            box-shadow: 0 4px 6px rgba(0,0,0,0.05);
            transition: all 0.5s ease;
            position: relative;
        }
        
        .num-block.highlight {
            background: var(--accent-color);
            color: white;
            border-color: var(--accent-color);
        }

        .controls-panel {
            grid-template-columns: 1fr 1.5fr; 
        }
    </style>
</head>
<body>
    <div class="container sim-container">
        <div class="nav-header">
            <a href="bucket_sort.php" class="back-link">← Back to Theory</a>
        </div>

        <header class="header">
            <h1>Bucket Sort Simulation</h1>
            <p class="subtitle">Visualizing Scatter-Gather for Float [0.0 - 1.0]</p>
        </header>

        <section class="card">
            <!-- Main Array Display -->
            <h3 style="text-align:center; margin-bottom:1rem; color:var(--text-muted);">Unsorted Input</h3>
            <div id="mainArray" class="array-container"></div>
            
            <hr style="border:0; border-top:1px solid #eee; margin:2rem 0;">

            <!-- Buckets -->
            <h3 style="text-align:center; margin-bottom:2rem; color:var(--text-muted);">Buckets (Ranges)</h3>
            <div class="buckets-grid">
                <!-- Generated by JS -->
            </div>
            
             <h3 style="text-align:center; margin-top:2rem; margin-bottom:1rem; color:var(--text-muted);">Sorted Output</h3>
            <div id="sortedArray" class="array-container"></div>
        </section>

        <div class="controls-panel">
            <div class="control-card">
                <h3 style="color: var(--accent-color);">Controls</h3>
                <div class="controls">
                    <button onclick="generateRandomArray()" class="btn btn-primary">Generate Random Floats</button>
                    <button onclick="startSort()" class="btn btn-info">Start Bucket Sort</button>
                </div>
            </div>

            <div class="control-card log-panel">
                 <h3 style="color: var(--accent-color);">Execution Log</h3>
                 <div id="log" class="operation-log" style="height: 150px;"></div>
            </div>
        </div>
    </div>

    <script>
        let arr = [];
        const SIZE = 10;
        const BUCKET_COUNT = 5; // 0.0-0.2, 0.2-0.4, etc.
        const DELAY = 800;
        
        const mainArrayDiv = document.getElementById('mainArray');
        const sortedArrayDiv = document.getElementById('sortedArray');
        const bucketsContainer = document.querySelector('.buckets-grid');
        const logDiv = document.getElementById('log');

        // Init Buckets
        for(let i=0; i<BUCKET_COUNT; i++) {
            const rangeStart = (i * (1/BUCKET_COUNT)).toFixed(1);
            const rangeEnd = ((i+1) * (1/BUCKET_COUNT)).toFixed(1);
            
            const bucket = document.createElement('div');
            bucket.className = 'bucket';
            bucket.id = `bucket-${i}`;
            bucket.innerHTML = `<span class="bucket-label">${rangeStart} - ${rangeEnd}</span>`;
            bucketsContainer.appendChild(bucket);
        }

        function generateRandomArray() {
            arr = [];
            for(let i=0; i<SIZE; i++) {
                // Random float 0.00 to 0.99
                arr.push(parseFloat(Math.random().toFixed(2)));
            }
            renderMainArray();
            sortedArrayDiv.innerHTML = ''; // Clear sorted
            clearBuckets();
            addLog('Generated new random floats.', 'info');
        }

        function renderMainArray() {
            mainArrayDiv.innerHTML = '';
            arr.forEach((num, idx) => {
                const el = document.createElement('div');
                el.className = 'num-block';
                el.id = `num-${idx}`;
                el.innerText = num.toFixed(2);
                mainArrayDiv.appendChild(el);
            });
        }

        function clearBuckets() {
            for(let i=0; i<BUCKET_COUNT; i++) {
                const rangeStart = (i * (1/BUCKET_COUNT)).toFixed(1);
                const rangeEnd = ((i+1) * (1/BUCKET_COUNT)).toFixed(1);
                const b = document.getElementById(`bucket-${i}`);
                b.innerHTML = `<span class="bucket-label">${rangeStart} - ${rangeEnd}</span>`;
            }
        }

        function addLog(msg, type='info') {
            const entry = document.createElement('div');
            entry.className = `log-entry log-${type}`;
            entry.innerText = `[${new Date().toLocaleTimeString()}] ${msg}`;
            logDiv.appendChild(entry);
            logDiv.scrollTop = logDiv.scrollHeight;
        }

        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        async function startSort() {
            addLog('Starting Bucket Sort...', 'info');
            sortedArrayDiv.innerHTML = ''; // Clear output

            // 1. Scatter
            addLog('Step 1: Scattering elements to buckets...', 'warning');
            
            let bucketsData = Array.from({length: BUCKET_COUNT}, () => []);

            for(let i=0; i<arr.length; i++) {
                const num = arr[i];
                // Index = floor(n * bucket_count)
                let idx = Math.floor(num * BUCKET_COUNT);
                if(idx >= BUCKET_COUNT) idx = BUCKET_COUNT - 1; // Handle 1.0 if strictly included
                
                bucketsData[idx].push(num);
                
                // Visual Move
                const sourceEl = document.getElementById(`num-${i}`);
                sourceEl.classList.add('highlight');
                await sleep(DELAY/2);
                
                const clone = sourceEl.cloneNode(true);
                clone.style.display = 'block';
                clone.style.width = 'fit-content';
                clone.style.margin = '5px auto';
                clone.classList.remove('highlight');
                
                const bucketDiv = document.getElementById(`bucket-${idx}`);
                bucketDiv.appendChild(clone);
                
                sourceEl.style.opacity = '0.2';
                
                addLog(`Value ${num} -> Bucket ${idx}`);
                await sleep(DELAY/2);
            }

            // 2. Sort Buckets
            addLog('Step 2: Sorting individual buckets...', 'warning');
            for(let i=0; i<BUCKET_COUNT; i++) {
                if(bucketsData[i].length > 0) {
                    addLog(`Sorting Bucket ${i}...`);
                     const bucketDiv = document.getElementById(`bucket-${i}`);
                     bucketDiv.style.borderColor = 'var(--accent-color)';
                     await sleep(DELAY);
                     
                     // Logic sort
                     bucketsData[i].sort((a,b) => a-b);
                     
                     // Visual update
                     // Clear content except label
                     const label = bucketDiv.querySelector('.bucket-label');
                     bucketDiv.innerHTML = '';
                     bucketDiv.appendChild(label);
                     
                     for(let val of bucketsData[i]) {
                         const el = document.createElement('div');
                         el.className = 'num-block';
                         el.style.width = 'fit-content';
                         el.style.margin = '5px auto';
                         el.style.background = '#d1fae5'; // Light green
                         el.innerText = val.toFixed(2);
                         bucketDiv.appendChild(el);
                     }
                     
                     await sleep(DELAY);
                     bucketDiv.style.borderColor = '';
                }
            }

            // 3. Gather
            addLog('Step 3: Gathering sorted elements...', 'success');
            for(let i=0; i<BUCKET_COUNT; i++) {
                for(let val of bucketsData[i]) {
                    const el = document.createElement('div');
                    el.className = 'num-block';
                    el.innerText = val.toFixed(2);
                    el.classList.add('highlight');
                    sortedArrayDiv.appendChild(el);
                    await sleep(200);
                }
            }

            addLog('Bucket Sort Complete!', 'success');
        }

        // Init
        generateRandomArray();
    </script>
</body>
</html>
