<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Radix Sort Simulation</title>
    <link rel="stylesheet" href="ds_style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet">
    <style>
        .sim-container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }

        .buckets-grid {
            display: grid;
            grid-template-columns: repeat(10, 1fr); /* 0-9 buckets */
            gap: 10px;
            margin-bottom: 2rem;
        }

        .bucket {
            min-height: 200px;
            background: rgba(102, 126, 234, 0.05);
            border: 2px dashed var(--border-color);
            border-radius: 10px;
            display: flex;
            flex-direction: column-reverse; /* Bottom up stack */
            padding: 10px;
            align-items: center;
            position: relative;
        }

        .bucket-label {
            position: absolute;
            bottom: -30px;
            font-weight: bold;
            color: var(--text-main);
        }

        .array-container {
            display: flex;
            justify-content: center;
            gap: 15px;
            margin-bottom: 2rem;
            min-height: 60px;
        }

        .num-block {
            padding: 10px 15px;
            background: white;
            border: 2px solid var(--primary-color);
            border-radius: 8px;
            font-weight: bold;
            font-family: 'Fira Code', monospace;
            box-shadow: 0 4px 6px rgba(0,0,0,0.05);
            transition: all 0.5s ease;
        }
        
        .num-block.highlight {
            background: var(--accent-color);
            color: white;
            border-color: var(--accent-color);
        }
        
        /* Highlight specific digit */
        .digit-active {
            color: #ef4444; /* Red for active digit */
            font-weight: 900;
        }

        .controls-panel {
            grid-template-columns: 1fr 1.5fr; 
        }
    </style>
</head>
<body>
    <div class="container sim-container">
        <div class="nav-header">
            <a href="radix_sort.php" class="back-link">← Back to Theory</a>
        </div>

        <header class="header">
            <h1>Radix Sort Simulation</h1>
            <p class="subtitle">LSD (Least Significant Digit) Visualization</p>
        </header>

        <section class="card">
            <!-- Main Array Display -->
            <h3 style="text-align:center; margin-bottom:1rem; color:var(--text-muted);">Current Array</h3>
            <div id="mainArray" class="array-container"></div>
            
            <hr style="border:0; border-top:1px solid #eee; margin:2rem 0;">

            <!-- Buckets 0-9 -->
            <h3 style="text-align:center; margin-bottom:1rem; color:var(--text-muted);">Digit Buckets</h3>
            <div class="buckets-grid">
                <!-- Generated by JS -->
            </div>
        </section>

        <div class="controls-panel">
            <div class="control-card">
                <h3 style="color: var(--accent-color);">Controls</h3>
                <div class="controls">
                    <button onclick="generateRandomArray()" class="btn btn-primary">Generate Random Array</button>
                    <button onclick="startSort()" class="btn btn-info">Start Radix Sort</button>
                </div>
            </div>

            <div class="control-card log-panel">
                 <h3 style="color: var(--accent-color);">Execution Log</h3>
                 <div id="log" class="operation-log" style="height: 150px;"></div>
            </div>
        </div>
    </div>

    <script>
        let arr = [];
        const SIZE = 8;
        const DELAY = 1000;
        const mainArrayDiv = document.getElementById('mainArray');
        const bucketsContainer = document.querySelector('.buckets-grid');
        const logDiv = document.getElementById('log');

        // Init Buckets
        for(let i=0; i<10; i++) {
            const bucket = document.createElement('div');
            bucket.className = 'bucket';
            bucket.id = `bucket-${i}`;
            bucket.innerHTML = `<span class="bucket-label">Digit ${i}</span>`;
            bucketsContainer.appendChild(bucket);
        }

        function generateRandomArray() {
            arr = [];
            for(let i=0; i<SIZE; i++) {
                // Random 2 or 3 digit number
                arr.push(Math.floor(Math.random() * 900) + 10);
            }
            renderMainArray();
            clearBuckets();
            addLog('Generated new array.', 'info');
        }

        function renderMainArray(highlightDigitIndex = -1) {
            mainArrayDiv.innerHTML = '';
            arr.forEach(num => {
                const el = document.createElement('div');
                el.className = 'num-block';
                
                // Highlight digit logic
                // Ensure num is string padded ?? No, standard string
                const sNum = num.toString();
                
                // digitIndex is from right (0 = ones, 1 = tens, etc)
                // string index is length - 1 - digitIndex
                
                if (highlightDigitIndex !== -1) {
                     const strIdx = sNum.length - 1 - highlightDigitIndex;
                     if(strIdx >= 0) {
                         const pre = sNum.substring(0, strIdx);
                         const dig = sNum.charAt(strIdx);
                         const post = sNum.substring(strIdx + 1);
                         el.innerHTML = `${pre}<span class="digit-active">${dig}</span>${post}`;
                     } else {
                         // Number is shorter than the digit we look for (treat as 0)
                         el.innerText = num; // Or show virtual 0? simplified for now.
                     }
                } else {
                    el.innerText = num;
                }
                
                mainArrayDiv.appendChild(el);
            });
        }

        function clearBuckets() {
            for(let i=0; i<10; i++) {
                // Keep label
                const b = document.getElementById(`bucket-${i}`);
                b.innerHTML = `<span class="bucket-label">Digit ${i}</span>`;
            }
        }

        function getMax(arr) {
            return Math.max(...arr);
        }

        function addLog(msg, type='info') {
            const entry = document.createElement('div');
            entry.className = `log-entry log-${type}`;
            entry.innerText = `[${new Date().toLocaleTimeString()}] ${msg}`;
            logDiv.appendChild(entry);
            logDiv.scrollTop = logDiv.scrollHeight;
        }

        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        async function startSort() {
            addLog('Starting Radix Sort...', 'info');
            
            const maxVal = getMax(arr);
            const digits = maxVal.toString().length;

            for (let exp = 0; exp < digits; exp++) {
                addLog(`Sorting by 10^${exp} place (Ones, Tens, etc.)`, 'warning');
                renderMainArray(exp); // Highlight current digit
                await sleep(DELAY);

                // 1. Distribute to Buckets
                let buckets = Array.from({length: 10}, () => []);

                const blocks = document.querySelectorAll('.num-block');
                
                for(let i=0; i<arr.length; i++) {
                    const num = arr[i];
                    // Get digit
                    // Math.floor(num / Math.pow(10, exp)) % 10
                    const digit = Math.floor(num / Math.pow(10, exp)) % 10;
                    
                    buckets[digit].push(num);
                    
                    // Visual Move
                    const clone = blocks[i].cloneNode(true);
                    
                    // Add to bucket visual
                    const bucketDiv = document.getElementById(`bucket-${digit}`);
                    // Simply append for now (stack visually bottom up due to flex-reverse)
                    // But we likely want queue behavior visually (top to bottom)? 
                    // CSS is flex-col-reverse, so appending adds to top. correct.
                    
                    // Actually, radix sort order in buckets must be maintained (stable).
                    // If visual stack is bottom-up, the first item added should be at bottom?
                    // flex-col-reverse: last child is at top. 
                    // So appending puts it at top.
                    // THIS IS WRONG for stable sort visual if we interpret "bottom" as "first".
                    // Let's adjust css to flex-col and justify-start?
                    // Or simply: appendChild places at end.
                    // If we want "Stack" look (new items on top), flex-col-reverse is good.
                    // But Radix is Queue based (FIFO) in buckets usually to be stable.
                    // Let's just create a block and append it.
                    
                    clone.style.margin = '2px 0';
                    bucketDiv.appendChild(clone);
                    blocks[i].style.opacity = '0.2'; // Dim original
                    
                    addLog(`Moved ${num} to Bucket ${digit}`);
                    await sleep(DELAY/2);
                }

                await sleep(DELAY);

                // 2. Collect from Buckets
                arr = [];
                addLog('Collecting back to Main Array...', 'warning');
                mainArrayDiv.innerHTML = ''; // Clear main
                
                for(let i=0; i<10; i++) {
                    if(buckets[i].length > 0) {
                        for(let val of buckets[i]) {
                             arr.push(val);
                             
                             // Add back to main visual
                             const el = document.createElement('div');
                             el.className = 'num-block';
                             el.innerText = val;
                             el.classList.add('highlight');
                             mainArrayDiv.appendChild(el);
                             await sleep(200);
                        }
                    }
                     // Clear bucket visual
                     const b = document.getElementById(`bucket-${i}`);
                     b.innerHTML = `<span class="bucket-label">Digit ${i}</span>`;
                }
                
                // Reset style
                const finalBlocks = document.querySelectorAll('.num-block');
                finalBlocks.forEach(b => b.classList.remove('highlight'));
                
                await sleep(DELAY);
            }

            renderMainArray(); // Final clean render
            addLog('Radix Sort Complete!', 'success');
        }

        // Init
        generateRandomArray();
    </script>
</body>
</html>
